// <auto-generated />
using System;
using CTS.Kanban;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CTS.Kanban.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231010181859_ColumnFK")]
    partial class ColumnFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CTS.Kanban.KanbanCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("KanbanColumnId")
                        .HasColumnType("integer");

                    b.Property<string>("StatusType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KanbanColumnId");

                    b.ToTable("KanbanCards");
                });

            modelBuilder.Entity("CTS.Kanban.KanbanColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KanbanColumns");
                });

            modelBuilder.Entity("CTS.Kanban.KanbanCard", b =>
                {
                    b.HasOne("CTS.Kanban.KanbanColumn", null)
                        .WithMany("KanbanCards")
                        .HasForeignKey("KanbanColumnId");
                });

            modelBuilder.Entity("CTS.Kanban.KanbanColumn", b =>
                {
                    b.Navigation("KanbanCards");
                });
#pragma warning restore 612, 618
        }
    }
}
