// <auto-generated />
using CTS.Kanban;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CTS.Kanban.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CTS.Kanban.KanbanCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KanbanColumnId")
                        .HasColumnType("integer");

                    b.Property<string>("KanbanColumnTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KanbanColumnId", "KanbanColumnTitle");

                    b.ToTable("KanbanCards");
                });

            modelBuilder.Entity("CTS.Kanban.KanbanColumn", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id", "Title");

                    b.ToTable("KanbanColumns");
                });

            modelBuilder.Entity("CTS.Kanban.KanbanCard", b =>
                {
                    b.HasOne("CTS.Kanban.KanbanColumn", "KanbanColumn")
                        .WithMany("KanbanCards")
                        .HasForeignKey("KanbanColumnId", "KanbanColumnTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KanbanColumn");
                });

            modelBuilder.Entity("CTS.Kanban.KanbanColumn", b =>
                {
                    b.Navigation("KanbanCards");
                });
#pragma warning restore 612, 618
        }
    }
}
